import {
  LayoutDashboard,
  ShoppingCart,
  Tags,
  Boxes,
  Users,
  Truck,
  BarChart3,
  Settings,
  Building2,
  BadgeDollarSign,
  ShieldCheck,
} from "lucide-react";
import type { Tenant, Role, Period, Section, ProductDraft, InventoryDraft } from "./types";

export const tenants: Tenant[] = [
  {
    id: "tenant-bakery",
    name: "Nusantara Bakery",
    plan: "Growth",
    status: "Active",
    logo: "NB",
    address: "Jl. Melati 18, Bandung",
    phone: "+62 22 8123 4501",
    hours: "07:00 - 21:00",
    owner: "Ayu Prameswari",
    currency: "IDR",
    taxRate: 11,
    receiptTemplate: "Struk termal ringkas dengan NPWD dan referensi QRIS",
    paymentMethods: ["Cash", "QRIS", "Bank Transfer", "E-Wallet", "Split Payment"],
    employees: [
      { name: "Ayu Prameswari", role: "SME Owner", status: "Active" },
      { name: "Raka", role: "Cashier", status: "Active" },
      { name: "Mira", role: "Cashier", status: "Off shift" },
    ],
    customers: [
      { name: "Dewi L.", phone: "+62 812 4000 1881", lastPurchase: "Hari ini, 09:42", lifetimeValue: 8400000 },
      { name: "Office Pantry", phone: "+62 811 7000 9910", lastPurchase: "Hari ini, 08:55", lifetimeValue: 21800000 },
      { name: "Pelanggan Umum", phone: "-", lastPurchase: "Hari ini, 09:18", lifetimeValue: 3260000 },
    ],
    suppliers: [
      { name: "Bandung Flour Supply", phone: "+62 22 7990 1001", openOrders: 2, purchaseHistory: 68000000 },
      { name: "Dairy Fresh ID", phone: "+62 21 5522 8820", openOrders: 1, purchaseHistory: 35400000 },
    ],
    products: [
      {
        id: "p-001",
        name: "Sourdough Loaf",
        category: "Bakery",
        sku: "BRD-SRD-01",
        barcode: "899100010001",
        purchasePrice: 18000,
        sellingPrice: 32000,
        stock: 36,
        minStock: 12,
        image: "linear-gradient(135deg, #fff7ed, #d97706)",
        soldToday: 28,
      },
      {
        id: "p-002",
        name: "Kopi Susu Botol",
        category: "Beverage",
        sku: "BEV-KSB-02",
        barcode: "899100010002",
        purchasePrice: 9000,
        sellingPrice: 18000,
        stock: 9,
        minStock: 18,
        image: "linear-gradient(135deg, #d6f3ff, #0f766e)",
        soldToday: 41,
      },
      {
        id: "p-003",
        name: "Croissant Butter",
        category: "Bakery",
        sku: "BRD-CRS-03",
        barcode: "899100010003",
        purchasePrice: 11000,
        sellingPrice: 24000,
        stock: 22,
        minStock: 16,
        image: "linear-gradient(135deg, #fefce8, #ea580c)",
        soldToday: 33,
      },
      {
        id: "p-004",
        name: "Cheese Cake Slice",
        category: "Dessert",
        sku: "DST-CCS-04",
        barcode: "899100010004",
        purchasePrice: 15000,
        sellingPrice: 34000,
        stock: 14,
        minStock: 10,
        image: "linear-gradient(135deg, #fefce8, #65a30d)",
        soldToday: 17,
      },
    ],
    transactions: [
      { id: "TRX-10291", cashier: "Raka", customer: "Dewi L.", total: 186000, method: "QRIS", time: "09:42", status: "Paid" },
      { id: "TRX-10290", cashier: "Mira", customer: "Pelanggan Umum", total: 74000, method: "Cash", time: "09:18", status: "Paid" },
      { id: "TRX-10289", cashier: "Raka", customer: "Office Pantry", total: 428000, method: "Bank Transfer", time: "08:55", status: "Pending" },
    ],
    inventoryLogs: [
      { product: "Kopi Susu Botol", type: "Stock Out", quantity: 41, note: "Transaksi penjualan" },
      { product: "Sourdough Loaf", type: "Stock In", quantity: 48, note: "Batch produksi pagi" },
      { product: "Cheese Cake Slice", type: "Adjustment", quantity: -2, note: "Kemasan rusak" },
    ],
  },
  {
    id: "tenant-grocery",
    name: "Toko Sembako Maju",
    plan: "Starter",
    status: "Active",
    logo: "TM",
    address: "Jl. Pasar Baru 7, Surabaya",
    phone: "+62 31 5531 8020",
    hours: "06:00 - 22:00",
    owner: "Bima Santoso",
    currency: "IDR",
    taxRate: 10,
    receiptTemplate: "Struk belanja detail dengan kode kasir dan split payment",
    paymentMethods: ["Cash", "QRIS", "E-Wallet", "Bank Transfer"],
    employees: [
      { name: "Bima Santoso", role: "SME Owner", status: "Active" },
      { name: "Nina", role: "Cashier", status: "Active" },
      { name: "Dimas", role: "Cashier", status: "Active" },
    ],
    customers: [
      { name: "Pak Rudi", phone: "+62 812 6400 2201", lastPurchase: "Hari ini, 10:02", lifetimeValue: 11750000 },
      { name: "Warung Sri", phone: "+62 813 7770 3131", lastPurchase: "Hari ini, 09:06", lifetimeValue: 31600000 },
      { name: "Pelanggan Umum", phone: "-", lastPurchase: "Hari ini, 09:49", lifetimeValue: 5190000 },
    ],
    suppliers: [
      { name: "Sumber Beras Timur", phone: "+62 31 7721 9008", openOrders: 3, purchaseHistory: 126000000 },
      { name: "Fresh Farm Surabaya", phone: "+62 31 8890 1130", openOrders: 1, purchaseHistory: 47200000 },
    ],
    products: [
      {
        id: "p-101",
        name: "Beras Premium 5kg",
        category: "Staple",
        sku: "STP-BRS-05",
        barcode: "899200010101",
        purchasePrice: 64000,
        sellingPrice: 78500,
        stock: 48,
        minStock: 20,
        image: "linear-gradient(135deg, #f8fafc, #64748b)",
        soldToday: 21,
      },
      {
        id: "p-102",
        name: "Minyak Goreng 2L",
        category: "Staple",
        sku: "STP-MYK-02",
        barcode: "899200010102",
        purchasePrice: 28500,
        sellingPrice: 35000,
        stock: 11,
        minStock: 24,
        image: "linear-gradient(135deg, #fef3c7, #ca8a04)",
        soldToday: 38,
      },
      {
        id: "p-103",
        name: "Sabun Cair Refill",
        category: "Household",
        sku: "HHD-SBN-03",
        barcode: "899200010103",
        purchasePrice: 13500,
        sellingPrice: 21000,
        stock: 29,
        minStock: 16,
        image: "linear-gradient(135deg, #e0f2fe, #2563eb)",
        soldToday: 12,
      },
      {
        id: "p-104",
        name: "Telur Ayam 1kg",
        category: "Fresh",
        sku: "FRS-TLR-01",
        barcode: "899200010104",
        purchasePrice: 24000,
        sellingPrice: 31500,
        stock: 17,
        minStock: 20,
        image: "linear-gradient(135deg, #fff1f2, #be123c)",
        soldToday: 24,
      },
    ],
    transactions: [
      { id: "TRX-88021", cashier: "Nina", customer: "Pak Rudi", total: 238500, method: "E-Wallet", time: "10:02", status: "Paid" },
      { id: "TRX-88020", cashier: "Dimas", customer: "Pelanggan Umum", total: 66500, method: "Cash", time: "09:49", status: "Paid" },
      { id: "TRX-88019", cashier: "Nina", customer: "Warung Sri", total: 518000, method: "Bank Transfer", time: "09:06", status: "Paid" },
    ],
    inventoryLogs: [
      { product: "Minyak Goreng 2L", type: "Stock Out", quantity: 38, note: "Transaksi penjualan" },
      { product: "Beras Premium 5kg", type: "Stock In", quantity: 80, note: "Pengiriman dari pemasok" },
      { product: "Telur Ayam 1kg", type: "Adjustment", quantity: -4, note: "Telur pecah/rusak" },
    ],
  },
];

export const roles: Role[] = ["Super Admin", "SME Owner", "Cashier"];
export const periods: Period[] = ["Daily", "Weekly", "Monthly", "Yearly", "Custom"];
export const navItems: { label: Section; icon: typeof LayoutDashboard }[] = [
  { label: "Dashboard", icon: LayoutDashboard },
  { label: "Sales", icon: ShoppingCart },
  { label: "Products", icon: Tags },
  { label: "Inventory", icon: Boxes },
  { label: "Customers", icon: Users },
  { label: "Suppliers", icon: Truck },
  { label: "Reports", icon: BarChart3 },
  { label: "Settings", icon: Settings },
];

export const platformStats = [
  { label: "UMKM Aktif", value: "248", icon: Building2, accent: "text-teal-700" },
  { label: "GMV Bulanan", value: "Rp 8.4M", icon: BadgeDollarSign, accent: "text-amber-700" },
  { label: "Kasir Aktif", value: "1.932", icon: Users, accent: "text-sky-700" },
  { label: "Uptime", value: "99.98%", icon: ShieldCheck, accent: "text-emerald-700" },
];

export const architectureItems = [
  { label: "Frontend", value: "Next.js App Router, React, Tailwind CSS" },
  { label: "Lapisan API", value: "REST contract siap untuk layanan NestJS" },
  { label: "Batasan Data", value: "ID Tenant membatasi produk, staf, laporan, dan struk belanja" },
  { label: "Modul Masa Depan", value: "Akuntansi, CRM, loyalitas pelanggan, marketplace, dan aplikasi mobile" },
];

export const emptyProductDraft: ProductDraft = {
  name: "",
  category: "",
  sku: "",
  barcode: "",
  purchasePrice: "",
  sellingPrice: "",
  stock: "",
  minStock: "",
};

export const emptyInventoryDraft: InventoryDraft = {
  productId: "",
  type: "Stock In",
  quantity: "",
  note: "",
};
